# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'WorldMart2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorldMart2
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
  	pod 'Firebase/Storage'

end
